//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Единица времени.
    /// </summary>
    // *** Start programmer edit section *** (ЕдиницаВремени CustomAttributes)

    // *** End programmer edit section *** (ЕдиницаВремени CustomAttributes)
    public enum ЕдиницаВремени
    {
        
        // *** Start programmer edit section *** (ЕдиницаВремени.День CustomAttributes)

        // *** End programmer edit section *** (ЕдиницаВремени.День CustomAttributes)
        [Caption("День")]
        День,
        
        // *** Start programmer edit section *** (ЕдиницаВремени.Месяц CustomAttributes)

        // *** End programmer edit section *** (ЕдиницаВремени.Месяц CustomAttributes)
        [Caption("Месяц")]
        Месяц,
        
        // *** Start programmer edit section *** (ЕдиницаВремени.Год CustomAttributes)

        // *** End programmer edit section *** (ЕдиницаВремени.Год CustomAttributes)
        [Caption("Год")]
        Год,
        
        // *** Start programmer edit section *** (ЕдиницаВремени.Час CustomAttributes)

        // *** End programmer edit section *** (ЕдиницаВремени.Час CustomAttributes)
        [Caption("Час")]
        Час,
    }
}
