//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчет времени.
    /// </summary>
    // *** Start programmer edit section *** (РасчетВремени CustomAttributes)

    // *** End programmer edit section *** (РасчетВремени CustomAttributes)
    [AutoAltered()]
    [Caption("Расчет времени")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасчетВремениE", new string[] {
            "Дата as \'Дата\'",
            "Договор as \'Номер договора\'",
            "Договор.Статус as \'Статус\'",
            "Договор.Длительность as \'Длительность\'",
            "Договор.ЕдиницаВремени as \'Единица времени\'",
            "Использовано as \'Использовано\'",
            "Доступно as \'Доступно\'"})]
    [AssociatedDetailViewAttribute("РасчетВремениE", "ОказанныеУслуги", "ОказанныеУслугиE", true, "", "Оказанные услуги", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("РасчетВремениE", "Договор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("РасчетВремениL", new string[] {
            "Дата as \'Дата\'",
            "Договор.Номер as \'Номер договора\'",
            "Договор.Статус as \'Статус\'",
            "Договор.Длительность as \'Длительность\'",
            "Договор.ЕдиницаВремени as \'Единица времени\'",
            "Использовано as \'Использовано\'",
            "Доступно as \'Доступно\'"})]
    public class РасчетВремени : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private double fИспользовано;
        
        private double fДоступно;
        
        private IIS.Modul_ucheta.Договор fДоговор;
        
        private IIS.Modul_ucheta.DetailArrayOfОказанныеУслуги fОказанныеУслуги;
        
        // *** Start programmer edit section *** (РасчетВремени CustomMembers)

        // *** End programmer edit section *** (РасчетВремени CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РасчетВремени.Дата CustomAttributes)

        // *** End programmer edit section *** (РасчетВремени.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РасчетВремени.Дата Get start)

                // *** End programmer edit section *** (РасчетВремени.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РасчетВремени.Дата Get end)

                // *** End programmer edit section *** (РасчетВремени.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетВремени.Дата Set start)

                // *** End programmer edit section *** (РасчетВремени.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РасчетВремени.Дата Set end)

                // *** End programmer edit section *** (РасчетВремени.Дата Set end)
            }
        }
        
        /// <summary>
        /// Доступно.
        /// </summary>
        // *** Start programmer edit section *** (РасчетВремени.Доступно CustomAttributes)

        // *** End programmer edit section *** (РасчетВремени.Доступно CustomAttributes)
        public virtual double Доступно
        {
            get
            {
                // *** Start programmer edit section *** (РасчетВремени.Доступно Get start)

                // *** End programmer edit section *** (РасчетВремени.Доступно Get start)
                double result = this.fДоступно;
                // *** Start programmer edit section *** (РасчетВремени.Доступно Get end)

                // *** End programmer edit section *** (РасчетВремени.Доступно Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетВремени.Доступно Set start)

                // *** End programmer edit section *** (РасчетВремени.Доступно Set start)
                this.fДоступно = value;
                // *** Start programmer edit section *** (РасчетВремени.Доступно Set end)

                // *** End programmer edit section *** (РасчетВремени.Доступно Set end)
            }
        }
        
        /// <summary>
        /// Использовано.
        /// </summary>
        // *** Start programmer edit section *** (РасчетВремени.Использовано CustomAttributes)

        // *** End programmer edit section *** (РасчетВремени.Использовано CustomAttributes)
        public virtual double Использовано
        {
            get
            {
                // *** Start programmer edit section *** (РасчетВремени.Использовано Get start)

                // *** End programmer edit section *** (РасчетВремени.Использовано Get start)
                double result = this.fИспользовано;
                // *** Start programmer edit section *** (РасчетВремени.Использовано Get end)

                // *** End programmer edit section *** (РасчетВремени.Использовано Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетВремени.Использовано Set start)

                // *** End programmer edit section *** (РасчетВремени.Использовано Set start)
                this.fИспользовано = value;
                // *** Start programmer edit section *** (РасчетВремени.Использовано Set end)

                // *** End programmer edit section *** (РасчетВремени.Использовано Set end)
            }
        }
        
        /// <summary>
        /// Расчет времени.
        /// </summary>
        // *** Start programmer edit section *** (РасчетВремени.Договор CustomAttributes)

        // *** End programmer edit section *** (РасчетВремени.Договор CustomAttributes)
        [PropertyStorage(new string[] {
                "Договор"})]
        [NotNull()]
        public virtual IIS.Modul_ucheta.Договор Договор
        {
            get
            {
                // *** Start programmer edit section *** (РасчетВремени.Договор Get start)

                // *** End programmer edit section *** (РасчетВремени.Договор Get start)
                IIS.Modul_ucheta.Договор result = this.fДоговор;
                // *** Start programmer edit section *** (РасчетВремени.Договор Get end)

                // *** End programmer edit section *** (РасчетВремени.Договор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетВремени.Договор Set start)

                // *** End programmer edit section *** (РасчетВремени.Договор Set start)
                this.fДоговор = value;
                // *** Start programmer edit section *** (РасчетВремени.Договор Set end)

                // *** End programmer edit section *** (РасчетВремени.Договор Set end)
            }
        }
        
        /// <summary>
        /// Расчет времени.
        /// </summary>
        // *** Start programmer edit section *** (РасчетВремени.ОказанныеУслуги CustomAttributes)

        // *** End programmer edit section *** (РасчетВремени.ОказанныеУслуги CustomAttributes)
        public virtual IIS.Modul_ucheta.DetailArrayOfОказанныеУслуги ОказанныеУслуги
        {
            get
            {
                // *** Start programmer edit section *** (РасчетВремени.ОказанныеУслуги Get start)

                // *** End programmer edit section *** (РасчетВремени.ОказанныеУслуги Get start)
                if ((this.fОказанныеУслуги == null))
                {
                    this.fОказанныеУслуги = new IIS.Modul_ucheta.DetailArrayOfОказанныеУслуги(this);
                }
                IIS.Modul_ucheta.DetailArrayOfОказанныеУслуги result = this.fОказанныеУслуги;
                // *** Start programmer edit section *** (РасчетВремени.ОказанныеУслуги Get end)

                // *** End programmer edit section *** (РасчетВремени.ОказанныеУслуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетВремени.ОказанныеУслуги Set start)

                // *** End programmer edit section *** (РасчетВремени.ОказанныеУслуги Set start)
                this.fОказанныеУслуги = value;
                // *** Start programmer edit section *** (РасчетВремени.ОказанныеУслуги Set end)

                // *** End programmer edit section *** (РасчетВремени.ОказанныеУслуги Set end)
            }
        }
        
        // *** Start programmer edit section *** (РасчетВремени.Отправить CustomAttributes)

        // *** End programmer edit section *** (РасчетВремени.Отправить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Отправить()
        {
            // *** Start programmer edit section *** (РасчетВремени.Отправить method implementation)

            return;
            // *** End programmer edit section *** (РасчетВремени.Отправить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасчетВремениE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетВремениE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетВремениE", typeof(IIS.Modul_ucheta.РасчетВремени));
                }
            }
            
            /// <summary>
            /// "РасчетВремениL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетВремениL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетВремениL", typeof(IIS.Modul_ucheta.РасчетВремени));
                }
            }
        }
    }
}
