//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуги.
    /// </summary>
    // *** Start programmer edit section *** (Услуги CustomAttributes)

    // *** End programmer edit section *** (Услуги CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УслугиE", new string[] {
            "Наименование as \'Наименование\'",
            "ЗатрачВремя as \'Затраченное время\'",
            "ЕдиницаВремени as \'Единица времени\'"})]
    [View("УслугиL", new string[] {
            "Наименование as \'Наименование\'",
            "ЗатрачВремя as \'Затраченное время\'",
            "ЕдиницаВремени as \'Единица времени\'"})]
    public class Услуги : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Modul_ucheta.Услуга fНаименование;
        
        private double fЗатрачВремя;
        
        private IIS.Modul_ucheta.ЕдиницаВремени fЕдиницаВремени;
        
        // *** Start programmer edit section *** (Услуги CustomMembers)

        // *** End programmer edit section *** (Услуги CustomMembers)

        
        /// <summary>
        /// ЕдиницаВремени.
        /// </summary>
        // *** Start programmer edit section *** (Услуги.ЕдиницаВремени CustomAttributes)

        // *** End programmer edit section *** (Услуги.ЕдиницаВремени CustomAttributes)
        public virtual IIS.Modul_ucheta.ЕдиницаВремени ЕдиницаВремени
        {
            get
            {
                // *** Start programmer edit section *** (Услуги.ЕдиницаВремени Get start)

                // *** End programmer edit section *** (Услуги.ЕдиницаВремени Get start)
                IIS.Modul_ucheta.ЕдиницаВремени result = this.fЕдиницаВремени;
                // *** Start programmer edit section *** (Услуги.ЕдиницаВремени Get end)

                // *** End programmer edit section *** (Услуги.ЕдиницаВремени Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуги.ЕдиницаВремени Set start)

                // *** End programmer edit section *** (Услуги.ЕдиницаВремени Set start)
                this.fЕдиницаВремени = value;
                // *** Start programmer edit section *** (Услуги.ЕдиницаВремени Set end)

                // *** End programmer edit section *** (Услуги.ЕдиницаВремени Set end)
            }
        }
        
        /// <summary>
        /// ЗатрачВремя.
        /// </summary>
        // *** Start programmer edit section *** (Услуги.ЗатрачВремя CustomAttributes)

        // *** End programmer edit section *** (Услуги.ЗатрачВремя CustomAttributes)
        public virtual double ЗатрачВремя
        {
            get
            {
                // *** Start programmer edit section *** (Услуги.ЗатрачВремя Get start)

                // *** End programmer edit section *** (Услуги.ЗатрачВремя Get start)
                double result = this.fЗатрачВремя;
                // *** Start programmer edit section *** (Услуги.ЗатрачВремя Get end)

                // *** End programmer edit section *** (Услуги.ЗатрачВремя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуги.ЗатрачВремя Set start)

                // *** End programmer edit section *** (Услуги.ЗатрачВремя Set start)
                this.fЗатрачВремя = value;
                // *** Start programmer edit section *** (Услуги.ЗатрачВремя Set end)

                // *** End programmer edit section *** (Услуги.ЗатрачВремя Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Услуги.Наименование CustomAttributes)

        // *** End programmer edit section *** (Услуги.Наименование CustomAttributes)
        public virtual IIS.Modul_ucheta.Услуга Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Услуги.Наименование Get start)

                // *** End programmer edit section *** (Услуги.Наименование Get start)
                IIS.Modul_ucheta.Услуга result = this.fНаименование;
                // *** Start programmer edit section *** (Услуги.Наименование Get end)

                // *** End programmer edit section *** (Услуги.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуги.Наименование Set start)

                // *** End programmer edit section *** (Услуги.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Услуги.Наименование Set end)

                // *** End programmer edit section *** (Услуги.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УслугиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УслугиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УслугиE", typeof(IIS.Modul_ucheta.Услуги));
                }
            }
            
            /// <summary>
            /// "УслугиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УслугиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УслугиL", typeof(IIS.Modul_ucheta.Услуги));
                }
            }
        }
    }
}
